Revert "giflib: bump to latest"
This reverts commit 405a5f26d6f25bdc969cf566902ab09795b17119.

breaks API compat (building liblepton):
gifio.c:406:5: error: too few arguments to function 'EGifCloseFile'
gifio.c:329:5: error: too few arguments to function 'EGifOpenFileHandle'
gifio.c:189:5: error: too few arguments to function 'DGifCloseFile'
gifio.c:92:5: error: too few arguments to function 'DGifOpenFileHandle'