tor: disable -fPIE which is currently incompatible with -fstack-protector
this caused a build error on i386 with the default toolchain
undefined reference to `__stack_chk_fail_local'

for some reason, it didn't happen on x86_64 with gcc 4.7.3.