mesalib: bump to latest and enable nouveau gallium driver
gallium was previously completely disabled, as i mistakenly believed
that it depends on LLVM.
however, it's only required for the radeonsi and llvmpipe drivers,
plus for r600's openCL support, according to nouveau developers.
with nouveau gallium driver enabled, nouveau_dri.so gets built which is
required for wine's direct draw/direct 3d support.

additionally, "xa" was disabled, since the Makefile rules for
libxatracker.so use some hacks (-nostdlib, etc) which cause link errors
(libgcc2.c:1180: undefined reference to `_Unwind_Resume').
according to http://git.alpinelinux.org/cgit/aports/tree/main/mesa/APKBUILD
this is functionality related to vmware, which we dont need anyway.

mesa-10.patch was taken from alpine.