fix musl 0.9.13 regressions related to tcp.h
same thing for strace and iptables:

/usr/include/linux/tcp.h:24:8: error: redefinition of 'struct tcphdr'
/usr/include/netinet/tcp.h:38:8: note: originally defined here