Revert "gcc473/474: always emit a proper libgcc link command"
This reverts commit 97511cf915edf0fdc752e94f4f903d50b2cfe934.

breaks "file":
gcc -Wl,-static -static-libgcc [...] -o file file.o  ./.libs/libmagic.a -lz
file.c:(.text.unlikely.usage+0x1d): undefined reference to `fprintf'